### PR TITLE
IDVA5-787 -compare the transactionId against transactionId stored in the db

### PR DESCRIPTION
**Pull request by swalke-ch**
change to compare the passed transactionId against transactionId stored in the mongodb

https://companieshouse.atlassian.net/browse/IDVA5-787

### Type of change

* [ ] Bug fix
* [x ] New feature
* [ ] Breaking change
* [ ] Infrastructure change

### Pull request checklist

* [ x] I have added unit tests for new code that I have added
* [ ] I have added/updated functional tests where appropriate
* [ ] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)

__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by sampankumar — APPROVED** [review]

**Review by ttingle-ch — APPROVED** [review]
LGTM

**Pull request merged**
